### ISSUE TITLE
upload-cloud.sh cron job

### ISSUE THREAD

**Issue by trandrew** [jaketame/plexacd#3]
I currently have the cron statement in crontab -e:
`30 2 * * * /opt/plexacd/upload-cloud.sh`

In /var/log/cron.log, it shows that it runs the statement at 2:30am, but I don't think the actual script runs because when I check in the morning, /opt/plexacd/logs/rclone-*.log's have nothing new, and my new media files are still on my local storage. Any idea?

**Comment by jaketame** [comment]
Did you update the .conf file with your media directories?

On 2 Mar 2017, at 22:24, Andrew Tran <notifications@github.com> wrote:

I currently have the cron statement in crontab -e:
30 2 * * * /opt/plexacd/upload-cloud.sh

In /var/log/cron.log, it shows that it runs the statement at 2:30am, but I don't think the actual script runs because when I check in the morning, /opt/plexacd/logs/rclone-*.log's have nothing new, and my new media files are still on my local storage. Any idea?

**Comment by trandrew** [comment]
Yes they all have complete paths.

```
# Directories 
PLEXACD="/opt/plexacd"
LOCALDIR="/media/plex/wdmedia/PlexACD"
LOCALTV="/media/plex/wdmedia/PlexACD/TV"
LOCALMV="/media/plex/wdmedia/PlexACD/Movies"
MEDIADIR="/home/plex/media"
REMOTENAME="acd-crypt"
REMOTETV="acd-crypt:TV/"
REMOTEMV="acd-crypt:Movies/"
ACDCRYPT="/home/plex/.acd-crypt/"
```
Don't know if this is related but I also have `@reboot /bin/sleep 60 ; /opt/plexacd/mount-crypt.sh`, and that works fine.

**Comment by jaketame** [comment]
Hmm paths look correct, can you manually run the following

rclone move --exclude partial~ --log-file=/opt/plexacd/logs/rclone-tv.log --transfers 10 --acd-upload-wait-per-gb=10s /media/plex/wdmedia/PlexACD/TV acd-crypt:TV/

**Comment by trandrew** [comment]
The script works if I manually execute it in my Terminal. Just doesn’t fire during cron job.

**Comment by jaketame** [comment]
did you chmod +x /opt/plexacd/* ?

**Comment by trandrew** [comment]
Yes sir. Here are the permission details:

-rwxr-xr-x 1 plex plex  922 Feb 26 21:08 upload-cloud.sh

**Comment by jaketame** [comment]
Can you check to see if you have 'flock' installed.

**Comment by trandrew** [comment]
Yes I have flock installed.

It seems the script did load this morning at 2:30am as I just checked rclone-tv.log and saw it uploaded episodes downloaded yesterday. 

I did reinstall rclone into usr/bin/rclone instead of usr/sbin/rclone yesterday. Maybe this fixed it?

**Comment by jaketame** [comment]
Most likely yes.
