### ISSUE TITLE
mount: special device overlay does not exist

### ISSUE THREAD

**Issue by trandrew** [jaketame/plexacd#4]
```
mount: special device overlay does not exist
[2017_03_03 18:44:19]: Failed to mount unionfs of /data/.local and /data/.acd-crypt/. please retry
rm: missing operand
Try 'rm --help' for more information.
```
Getting this error after running mount-crypt.sh on Ubuntu 16.04 LTS

**Comment by jaketame** [comment]
Sounds like Ubuntu doesn't include Overlay into the kernel. You will need to install the custom kernel.

**Comment by trandrew** [comment]
I did install the custom kernel and verified it with uname.

**Comment by jaketame** [comment]
Ok do all the directories exist in the mount command?

**Comment by trandrew** [comment]
Yes they all exist and are empty directories.

**Comment by jaketame** [comment]
I think I know what the issue is, need to update the script. Not at at computer today tho

On 4 Mar 2017, at 09:01, Andrew Tran <notifications@github.com> wrote:

Yes they all exist and are empty directories.

**Comment by jaketame** [comment]
https://github.com/jaketame/plexacd/commit/b100027a8de40e544e8eb8194576d3dc3f5955b4

I believe i've resolved this, please pull latest file

**Comment by jaketame** [comment]
How you getting on?

**Comment by trandrew** [comment]
Scripts are working with the latest update. Thanks!
