### ISSUE TITLE
Can overlayfs work with the local folder on external storage?

### ISSUE THREAD

**Issue by trandrew** [jaketame/plexacd#8]
The script works wonderfully when I have all the local directories on my main drive. If I try to run the script using my external drive for the local folder(s), I get a mount error. Is this a limitation to overlayfs?

Error:
````
mount: wrong fs type, bad option, bad superblock on overlay,
       missing codepage or helper program, or other error

       In some cases useful info is found in syslog - try
       dmesg | tail or so.
[2017_03_07 10:04:42]: Failed to mount overlayfs of /media/plex/wdmedia/PlexACD and /home/plex/.acd-crypt/. please retry
rm: missing operand
Try 'rm --help' for more information.
`````

**Comment by jaketame** [comment]
Your work dir needs to be on the same file system as the upper dir

On 7 Mar 2017, at 18:13, Andrew Tran <notifications@github.com> wrote:

The script works wonderfully when I have all the local directories on my main drive. If I try to run the script using my external drive, I get a mount error. Is this a limitation to overlayfs?

Error:
`mount: wrong fs type, bad option, bad superblock on overlay,
missing codepage or helper program, or other error

   In some cases useful info is found in syslog - try
   dmesg | tail or so.
[2017_03_07 10:04:42]: Failed to mount overlayfs of /media/plex/wdmedia/PlexACD and /home/plex/.acd-crypt/. please retry
rm: missing operand
Try 'rm --help' for more information.
`
